### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by FredyR4zox** [TykTechnologies/tyk-operator#351]
Hi,

I've been trying to getting tyk gateway to work but i haven't been successful.
At first, i tried using the API Definitions templates with the Ingress but it worked for some seconds and then puff, it stopped working without me changing anything. Only sending more requests. Not even restarting the pods corrected it.
I have tried with TLS and without TLS, only using API Definitions without the Ingress (templating). and still nothing.
Sometimes it works but then stops working (rarely works).
The errors are mostly 404 Not found errors but sometimes they don't even reach the gateway.
I have the log_level at debug but it isn't helpful.

Does anyone know what is going on with this?

Here goes my files and some screenshots of the API Definitions and such.

Thank you.

![image](https://user-images.githubusercontent.com/6351888/129767231-bfc8034f-e071-4ca4-8270-41e4bc66568d.png)

![image](https://user-images.githubusercontent.com/6351888/129767317-c85d11a7-0afe-45ab-9e2e-a8b846824633.png)

![image](https://user-images.githubusercontent.com/6351888/129767417-60f09269-881b-4f34-b009-c07a52e18075.png)

![image](https://user-images.githubusercontent.com/6351888/129767582-fb161139-e4d2-4276-ac53-5b62e2869c28.png)

When I set the protocol to https in the API Definition, an error occurs. It says "implement me".
It comes from here:
https://github.com/TykTechnologies/tyk-operator/blob/master/pkg/client/gateway/client.go line 61

**Comment by asoorm** [comment]
Hello and thank you for your query @FredyR4zox .

It looks like you are using Tyk Operator with an Open Source Gateway installation. Tyk Operator only operates on a single Gateway, not a cluster of Gateways - it looks like the reason it kind of worked, then stopped, is because the K8s service is RR load balancing to 2 nodes which don't work, and 1 node which does. This is a licensing limitation.

https://github.com/TykTechnologies/tyk-operator/blob/master/docs/installation/installation.md#tyk-licensing

Would you like me to put you in-touch with an Account Exec / Solution Architect to set you up with a PoC / Trial License?

**Comment by FredyR4zox** [comment]
Hi @asoorm,

Ah, makes sense :/ I will use only one gateway then. Right now I don't need the full gateway.
But can I serve services from different namespaces? I can have 10 services from the default namespace and other 10 from other namespace?
And what about the https thing ("implement me")? Can I provide my certificate to the gateway so that i don't use a self signed cert?

Thank you for your answer.

**Comment by asoorm** [comment]
> But can I serve services from different namespaces? I can have 10 services from the default namespace and other 10 from other namespace?

Absolutely - yes you can

> Can I provide my certificate to the gateway so that i don't use a self signed cert?

https://tyk.io/docs/basic-config-and-security/security/tls-and-ssl/#tykconf

You can load your TLS certificate into Tyk by mounting it as a volume & referencing it in the tyk.conf, or via env var.
